kind: pipeline
name: default

steps:
- name: test
  image: brazildatacube/r-webservices:1.0.0
  commands:
  - R CMD build .
  - set -e; R CMD check *.tar.gz >&1 | tee stdfile && cat stdfile | (grep -E "(WARNING|ERROR)" > /dev/null) && exit 1 || exit 0

- name: coverage
  image: brazildatacube/r-webservices:1.0.0
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
  - R -e 'install.packages("pacman"); pacman::p_load(desc::desc_get_deps()[desc::desc_get_deps()[["type"]] != "Depends",][["package"]], install = T, update = F, character.only = T)'
  - R -e 'withr::with_envvar(c(NOT_CRAN="true"), covr::codecov(quiet = FALSE))'
  when:
    event:
    - push
